import test from 'node:test';
import assert from 'node:assert/strict';
import {EncryptedConversation} from './conversation.mjs';
const ROOM='!pair:lab.invalid',ME='@a:lab.invalid',PEER='@b:lab.invalid';
class Ledger{constructor(){this.rows=new Map();}async open(){}async get(r,id){return this.rows.get(r+'|'+id);}async put(r,id,v){this.rows.set(r+'|'+id,{roomId:r,eventId:id,...v});}async list(r){return [...this.rows.values()].filter(v=>v.roomId===r);}}
function fixture(ledger=new Ledger()){
 const f={verified:true,sends:0,redactions:0,members:[ME,PEER],algorithm:'m.megolm.v1.aes-sha2',peerDevices:new Map([['B',{}]])};
 const content={'m.room.history_visibility':{history_visibility:'joined'},'m.room.join_rules':{join_rule:'invite'},'m.room.create':{'m.federate':false}};
 const room={getMyMembership:()=>f.members.includes(ME)?'join':'leave',getJoinedMembers:()=>f.members.map(userId=>({userId})),currentState:{getStateEvents:t=>({getContent:()=>t==='m.room.encryption'?{algorithm:f.algorithm}:content[t]})}};
 const crypto={globalBlacklistUnverifiedDevices:true,getUserDeviceInfo:async()=>new Map([[ME,new Map([['A',{}]])],[PEER,f.peerDevices]]),getDeviceVerificationStatus:async()=>({isVerified:()=>f.verified})};
 const client={getRoom:()=>room,getUserId:()=>ME,getDeviceId:()=> 'A',getCrypto:()=>crypto,sendTextMessage:async()=>{f.sends++;return {event_id:'$sent'};},redactEvent:async(r,id)=>{assert.equal(r,ROOM);f.redactions++;if(f.rejectDelete)throw new Error('network_unavailable');return {event_id:'$redaction'};}};
 f.conversation=new EncryptedConversation({client,roomId:ROOM,peerUserId:PEER,peerDeviceId:'B',ledger});f.client=client;f.ledger=ledger;return f;
}
function message(id='$m',roomId=ROOM){return {getRoomId:()=>roomId,getId:()=>id,getType:()=> 'm.room.message',isRedacted:()=>false,isEncrypted:()=>true,isDecryptionFailure:()=>false,getSender:()=>PEER,getContent:()=>({msgtype:'m.text',body:'synthetic-only'}),getTs:()=>1};}

test('verified encrypted pair sends through SDK',async()=>{const f=fixture();await f.conversation.initialize();await f.conversation.send('fixture');assert.equal(f.sends,1);});
test('missing encryption has no plaintext fallback',async()=>{const f=fixture();await f.conversation.initialize();f.algorithm=undefined;await assert.rejects(f.conversation.send('fixture'),/encryption_required/);assert.equal(f.sends,0);});
test('unverified replacement device blocks sends',async()=>{const f=fixture();await f.conversation.initialize();f.verified=false;await assert.rejects(f.conversation.send('fixture'),/verification_required/);assert.equal(f.sends,0);});
test('extra participant blocks sends',async()=>{const f=fixture();await f.conversation.initialize();f.members.push('@third:lab.invalid');await assert.rejects(f.conversation.send('fixture'),/two_participants/);});
test('extra peer device blocks sends',async()=>{const f=fixture();await f.conversation.initialize();f.peerDevices.set('UNBOUND',{});await assert.rejects(f.conversation.send('fixture'),/one_bound_device/);});
test('plaintext and unrelated room events are not shown',async()=>{const f=fixture();await f.conversation.initialize();const plain=message();plain.isEncrypted=()=>false;await f.conversation.ingest(plain);await f.conversation.ingest(message('$other','!other:lab.invalid'));assert.deepEqual(f.conversation.snapshot(),[]);});
test('redaction arriving before message prevents replay resurrection',async()=>{const f=fixture();await f.conversation.initialize();await f.conversation.applyServerRedaction('$m');await f.conversation.ingest(message());assert.deepEqual(f.conversation.snapshot(),[]);});
test('persisted deletion remains effective after reload',async()=>{const ledger=new Ledger();const f=fixture(ledger);await f.conversation.initialize();await f.conversation.applyServerRedaction('$m');const next=fixture(ledger);await next.conversation.initialize();await next.conversation.ingest(message());assert.deepEqual(next.conversation.snapshot(),[]);});
test('delete requires no peer approval, verification or online peer',async()=>{const f=fixture();await f.conversation.initialize();await f.conversation.ingest(message());f.verified=false;f.members=[ME];const result=await f.conversation.deleteForBoth('$m');assert.equal(f.redactions,1);assert.equal(result.status,'server_redacted');assert.equal(result.cleanup,'unconfirmed');assert.deepEqual(f.conversation.snapshot(),[]);});
test('network failure remains pending and can retry after reconnect',async()=>{const f=fixture();await f.conversation.initialize();f.rejectDelete=true;await assert.rejects(f.conversation.deleteForBoth('$m'));assert.equal((await f.ledger.get(ROOM,'$m')).status,'pending_server');f.rejectDelete=false;await f.conversation.retryPendingDeletes();assert.equal((await f.ledger.get(ROOM,'$m')).status,'server_redacted');});
test('duplicate delete requests use one server operation',async()=>{const f=fixture();await f.conversation.initialize();await Promise.all([f.conversation.deleteForBoth('$m'),f.conversation.deleteForBoth('$m')]);assert.equal(f.redactions,1);});
test('ledger failure releases delete lock rather than pretending success',async()=>{const f=fixture();await f.conversation.initialize();const put=f.ledger.put.bind(f.ledger);f.ledger.put=async()=>{throw new Error('quota');};await assert.rejects(f.conversation.deleteForBoth('$m'));assert.equal(f.redactions,0);f.ledger.put=put;await f.conversation.deleteForBoth('$m');assert.equal(f.redactions,1);});
test('in-flight stale read cannot resurrect a locally hidden message',async()=>{const f=fixture();await f.conversation.initialize();let release;const original=f.ledger.get.bind(f.ledger);f.ledger.get=async(r,id)=>id==='$m'?new Promise(resolve=>{release=resolve;}):original(r,id);const incoming=f.conversation.ingest(message());await Promise.resolve();f.ledger.get=original;const deletion=f.conversation.deleteForBoth('$m');release(undefined);await Promise.all([incoming,deletion]);assert.deepEqual(f.conversation.snapshot(),[]);});

test('one failed pending deletion does not starve later rows',async()=>{const f=fixture();await f.conversation.initialize();await f.ledger.put(ROOM,'$first',{status:'pending_server'});await f.ledger.put(ROOM,'$second',{status:'pending_server'});f.client.redactEvent=async(r,id)=>{if(id==='$first')throw new Error('first_failed');return {event_id:'$second_redaction'};};const batch=await f.conversation.retryPendingDeletes();assert.deepEqual(batch.failedEventIds,['$first']);assert.equal((await f.ledger.get(ROOM,'$second')).status,'server_redacted');});
test('acknowledged server deletion survives metadata failure without resending',async()=>{const f=fixture();await f.conversation.initialize();const put=f.ledger.put.bind(f.ledger);let fail=true;f.ledger.put=async(r,id,v)=>{if(v.status==='server_redacted'&&fail)throw new Error('quota');return put(r,id,v);};const first=await f.conversation.deleteForBoth('$m');assert.equal(first.status,'server_redacted');assert.equal(first.metadataPersistence,'failed');assert.equal(first.cleanup,'unconfirmed');assert.equal(f.redactions,1);fail=false;await f.conversation.retryPendingDeletes();assert.equal(f.redactions,1);assert.equal((await f.ledger.get(ROOM,'$m')).status,'server_redacted');});
test('network retries reuse a stable Matrix transaction identity',async()=>{const f=fixture();await f.conversation.initialize();const transactions=[];f.client.redactEvent=async(r,id,txn)=>{transactions.push(txn);if(transactions.length===1)throw new Error('timeout');return {event_id:'$ack'};};await assert.rejects(f.conversation.deleteForBoth('$m'));await f.conversation.retryPendingDeletes();assert.equal(transactions.length,2);assert.equal(transactions[0],transactions[1]);});
